deployment:
  tasks:
    - export APPPATH=/home/siatexglobal/laravel-app/
    - export PUBLICPATH=/home/siatexglobal/public_html/

    - /bin/mkdir -p $APPPATH
    - /bin/mkdir -p $PUBLICPATH

    # Copy ALL files to laravel-app (including hidden like .htaccess if any in root)
    - /bin/cp -a . $APPPATH

    # Remove git folder from deployed app
    - /bin/rm -rf $APPPATH/.git

    # Copy public files to public_html (includes .htaccess inside public)
    - /bin/cp -a $APPPATH/public/. $PUBLICPATH
